### ISSUE TITLE
how to format the output

### ISSUE THREAD

**Issue by Manjunath-PM** [awslabs/amazon-transcribe-streaming-sdk#53] opened 2021-08-20 08:51 UTC
aws transcribe is working fine, however the output is like this
This.
This is
This is a
This is a te
This is a test.
This is a test.

I only want the output as
This is a test.

I understand the repeatation line comes as streaming is very fast. how to do streaming so that one word go only once.

What changes need to be done in program simple_file.py orsimple_mic.py.

**Comment by nateprewitt** [comment] 2021-08-23 21:53
Resolving as a duplicate of #41.

**Closed as completed by nateprewitt** 2021-08-23 21:53 UTC
Labels: duplicate
